name: vip-gan
channels:
- pytorch
- defaults
dependencies:
- absl-py=0.7.0=py27_0
- backports=1.0=py27_1
- backports.weakref=1.0.post1=py27_0
- blas=1.0=mkl
- bleach=1.5.0=py27_0
- ca-certificates=2019.1.23=0
- certifi=2019.3.9=py27_0
- cffi=1.12.2=py27h2e261b9_1
- cudatoolkit=9.0=h13b8566_0
- cudnn=7.3.1=cuda9.0_0
- cupti=9.0.176=0
- enum34=1.1.6=py27_1
- freetype=2.9.1=h8a8886c_1
- funcsigs=1.0.2=py27_0
- futures=3.2.0=py27_0
- html5lib=0.9999999=py27_0
- intel-openmp=2019.3=199
- jpeg=9b=h024ee3a_2
- libedit=3.1.20181209=hc058e9b_0
- libffi=3.2.1=hd88cf55_4
- libgcc-ng=8.2.0=hdf63c60_1
- libgfortran-ng=7.3.0=hdf63c60_0
- libpng=1.6.36=hbc83047_0
- libprotobuf=3.6.1=hd408876_0
- libstdcxx-ng=8.2.0=hdf63c60_1
- libtiff=4.0.10=h2733197_2
- markdown=3.0.1=py27_0
- mkl=2018.0.3=1
- mkl_fft=1.0.6=py27h7dd41cf_0
- mkl_random=1.0.1=py27h4414c95_1
- mock=2.0.0=py27_0
- ncurses=6.1=he6710b0_1
- ninja=1.9.0=py27hfd86e86_0
- numpy=1.15.4=py27h1d66e8a_0
- numpy-base=1.15.4=py27h81de0dd_0
- olefile=0.46=py27_0
- openssl=1.1.1b=h7b6447c_1
- pathlib=1.0.1=py27_1
- pbr=5.1.3=py_0
- pillow=5.4.1=py27h34e0f95_0
- pip=19.0.3=py27_0
- protobuf=3.6.1=py27he6710b0_0
- pycparser=2.19=py27_0
- python=2.7.16=h9bab390_0
- readline=7.0=h7b6447c_5
- scipy=1.1.0=py27hfa4b5c9_1
- setuptools=40.8.0=py27_0
- six=1.12.0=py27_0
- sqlite=3.27.2=h7b6447c_0
- tensorflow-gpu=1.5.0=0
- tensorflow-gpu-base=1.5.0=py27h8a131e3_0
- tensorflow-tensorboard=1.5.1=py27hf484d3e_1
- tk=8.6.8=hbc83047_0
- torchvision=0.2.1=py27_0
- werkzeug=0.14.1=py27_0
- wheel=0.33.1=py27_0
- xz=5.2.4=h14c3975_4
- zlib=1.2.11=h7b6447c_3
- zstd=1.3.7=h0b5b093_0
- cuda90=1.0=h6433d27_0
- pytorch=0.4.0=py27_cuda9.0.176_cudnn7.1.2_1
